config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  # concerns:
  concern :members do
    resources :league_users
  end

  # resource routes:
  resources :users,             concerns: :members
  resources :leagues,           concerns: :members

  # session routes:
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'

  # sign-up routes:
  get    '/signup',             to: 'users#new'
  get    '/signup',             to: 'users#create'

  # non-controller pages:
  get 'landing/index'
  get 'landing/about'

  root 'landing#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord

  has_many :league_users
  has_many :users, :through => :league_users, dependent: :destroy

  has_many :seasons

  has_many :invites

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)
    @league.users << current_user
    owner = @league.league_users.last
    owner.toggle!(:league_admin)
    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :league_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/_league_users.html.erb
<% @league.users.where("league_users.league_admin = true").each do |u| %>
  <div class="league-user admin">
    <h3>
      <%= u.user_name %>
    </h3>
    <h5>
      League Admin
    </h5>
  </div>
<% end %>

<% @league.users.where("league_users.league_admin = false").each do |u| %>
  <div class="league-user member">
    <h3>
      <%= u.user_name %>
    </h3>
  </div>
<% end %>

app/views/leagues/_leagues.html.erb
<li>
  <%= league.name %>
</li>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<div class="league-container">

  <div class="header-container">

    <div class="league-header">
      <h1> <%= @league.name %></h1>
    </div>

    <div class="header-menu">
      <h3> League Home </h3>
      <h3> Standings </h3>
      <h3> Users </h3>
    </div>

  </div>

  <div class="league-content">

    <div class="league-table">
      <h1 class="content-header"> League Table </h1>
    </div>

    <div class="league-users">
      <h1 class="content-header"> Members </h1>
      <%= render 'league_users' %>
    </div>

  </div>

</div>



<% if logged_in? %>
  <% if current_user.leagues.include?(@league) %>

    <h4> You're already a member of this league </h4>

    <%= link_to "Leave this league", league_league_user_path(@league, current_user), :method => :delete %>

  <% else %>

  <%= form_with(model: [ @league, LeagueUser.new ]) do |form| %>
    <%= form.hidden_field :league_id,           :value => @league.id %>
    <%= form.hidden_field :user_id,             :value => current_user.id %>
    <%= form.submit "Join this league" %>
  <% end %>

  <% end %>
<% else %>

  <h4> Create an account to be able to join leagues! </h4>

<% end %>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>