config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  # concerns:
  concern :members do
    resources :league_users
  end

  # resource routes:
  resources :users,             concerns: :members
  resources :leagues,           concerns: :members

  # session routes:
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'

  # sign-up routes:
  get    '/signup',             to: 'users#new'
  get    '/signup',             to: 'users#create'

  # non-controller pages:
  get 'landing/index'
  get 'landing/about'

  root 'landing#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :league_users
  has_many :leagues, :through => :league_users, dependent: :destroy

  has_many :invitations,   :class_name => "Invite", :foreign_key => "recipient_id"
  has_many :sent_invites,  :class_name => "Invite", :foreign_key => "sender_id"

  attr_accessor :remember_token

  before_save { self.email_address = email_address.downcase }

  validates :user_name,           presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email_address,       presence: true, length: { maximum: 255 },
                                  format: { with: VALID_EMAIL_REGEX },
                                  uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password,            presence: true, length: { minimum: 6 }, allow_nil: true

  # hash digest
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # remember token:
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # remembers a user for persistent sessions:
  def remember
    self.remember_token = User.new_token
    update_attribute(:remeber_digest, User.digest(remember_token))
  end

  # matches token and digest:
  def authenticated?(remember_token)
    return false if remeber_digest.nil?
    BCrypt::Password.new(remeber_digest).is_password?(remember_token)
  end

  # forget a user:
  def forget
    update_attribute(:remeber_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :site_admin_user, only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        log_in @user
        flash[:success] = "Thanks for signing up!"
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email_address, :password, :password_confirmation)
    end

    #before filters?
    #confirms correct user:
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def site_admin_user
      redirect_to(root_url) unless current_user.site_admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <!-- Error Notices -->
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- Form fields -->
  <%= form.text_field :user_name, value: 'User Name' %>
  <%= form.text_field :email_address, value: 'Email Address' %>
  <%= form.text_field :password, value: 'Password' %>
  <%= form.text_field :password_confirmation, value: 'Confirm Password' %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <% if current_user.site_admin? && !current_user?(user) %>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Home', root_url %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
<%= link_to 'Home', root_url %> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="user-container">

  <h1>
    <%= @user.user_name %>
  </h1>

  <div class="user-leagues">

    <h2>
      My Leagues
    </h2>

    <% if @user.league_users.any? %>
      <% @user.league_users.each do |league_user| %>
        <h4>
          <%= league_user.league.name %>
        </h4>
      <% end %>
    <% else %>
      <p>
        You don't seem to be a member of any leagues.
      </p>
    <% end %>

    <h4>
      <%= link_to 'Start a new League', new_league_path %>
    </h4>

  </div>


  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

</div>