config/routes.rb
Rails.application.routes.draw do

  get 'seasons/new'

  # concerns:
  concern :members do
    resources :league_users
  end

  # resource routes:
  resources :users,             concerns: :members
  resources :leagues,           concerns: :members

  # session routes:
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'

  # sign-up routes:
  get    '/signup',             to: 'users#new'
  get    '/signup',             to: 'users#create'

  # non-controller pages:
  get 'landing/index'
  get 'landing/about'

  root 'landing#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="site-header">
  <h1> inHouse </h1>

  <div class="header-login">

    <% if logged_in? %>

    <div class="header-links">
      <%= link_to "#{current_user.user_name}", user_path(current_user) %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    </div>

    <% else %>

      <div class="header-form">
        <%= form_for(:session, url: login_path)      do |form| %>
          <%= form.text_field :email_address,        value: 'Email' %>
          <%= form.text_field :password,             value: 'Password' %>
          <%= form.submit "Log In" %>
        <% end %>
      </div>

    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>Inhouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="error-container">
      <% flash.each do |message_type, message| %>
        <div class="error error-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div id="yeild-container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  
  </body>

</html>